language: generic
matrix:
  include:
    - name: "Python 3.5"
      env:
        - PYTHON=3.5
        - PYTHONCMD=python3.5
    - name: "Python 3.6"
      env:
        - PYTHON=3.6
        - PYTHONCMD=python3.6
    - name: "Python 3.7"
      env:
        - PYTHON=3.7
        - PYTHONCMD=python3.7
    - name: "Python 3.8"
      env:
        - PYTHON=3.8
        - PYTHONCMD=python3.8
    # requires zc.buildout to become compatible
    #   https://github.com/buildout/buildout/issues/497
    # (yes we could ask buildout to run against a different python version
    #  but that would make the travis setup explode even more ...)
    # - name: "Python 3.9-dev"
    #   env:
    #     - PYTHON=3.9-dev
    #     - PYTHONCMD=python3.9
    # - name: "Python nightly"
    #   env:
    #     - PYTHON=nightly
    #     - PYTHONCMD=python3.9
script:
  - sudo apt-get install python3-venv libyaml-dev
  - curl -sSf -o python-$PYTHON.tar.bz2 https://storage.googleapis.com/travis-ci-language-archives/python/binaries/ubuntu/16.04/x86_64/python-$PYTHON.tar.bz2
  - sudo tar xjf python-$PYTHON.tar.bz2 --directory /
  - /opt/python/$PYTHON/bin/$PYTHONCMD -m venv .
  - pip install -U setuptools==35.0.2 zc.buildout setuptools-scm coveralls
  - bin/buildout -n
  - bin/pytest --cache-clear -p no:sugar --cov-report term-missing --cov src
after_success:
  - coveralls
cache:
  pip: true
notifications:
  webhooks:
    secure: PzGlaDBtvSoa3pY0cDyv8PDaYLCjXrjjf/RvAP70QZkIkSaSJefLg0ITaRdg6oObX0CmWIY5e5K9mCrQ8XWB4zr7cXci1/LqbBo8nd41Gpl846b080SIpZ436doXTNUl32CMJJitpA2WPR5kSxdzM3hVC50z9i4r27IrIE+zuGmImD3ovIjhrodWHU1/HSRb6HvH1YR5kRSShZBKYtcEmDq6xYOc+nibM64JeIdsTAAIaMoEprrk1987mPUU+uG+RMsOqBPW114iZ2/8T9Pf6dcIib6wbrVNX47n2/oNkKWjrVOA1tb+yDJ6l3j5gXLI+o06bYeX27GOU/N4voZUZdDHj2N5qhDmG/IVUYQHb1nQ9BMtu8y6Zn3QI39en+KXJ9pj+YRfskcog/GTFmsU+/Ud0GocaCJ6iPkbnf4SkHaSga2nSNiECAS7ZtuL5Y7iAhPf6c8GzZ4xQkpPxKJGBwkM/wpFFn11luz6fWho5PoGCYVuWLU0WCvgN/o3asC45D4woQW/NGJbJhRmw73Zzj6CPXz2KH9a9b/FYUoY070ivlDa3Wc00MK+mo6erXQBecnclh34qRnT4UfdI/Xan4zqfdrTtH7fEUzWxlHGT0yxvDR9Cg8g4A6wsx/qL9mDciWSDqueN7TOc4/6vwbpL61biTpMd6l1mzFa5ByQUdA=
