language: python
dist: xenial
python:
    - 3.5
install:
    - pip install -U setuptools==35.0.2 zc.buildout setuptools-scm coveralls
    - buildout -n
script:
    - bin/pytest --cache-clear -p no:sugar --cov-report term-missing --cov src
after_success:
    - coveralls
cache:
  pip: true
notifications:
  webhooks:
    secure: PzGlaDBtvSoa3pY0cDyv8PDaYLCjXrjjf/RvAP70QZkIkSaSJefLg0ITaRdg6oObX0CmWIY5e5K9mCrQ8XWB4zr7cXci1/LqbBo8nd41Gpl846b080SIpZ436doXTNUl32CMJJitpA2WPR5kSxdzM3hVC50z9i4r27IrIE+zuGmImD3ovIjhrodWHU1/HSRb6HvH1YR5kRSShZBKYtcEmDq6xYOc+nibM64JeIdsTAAIaMoEprrk1987mPUU+uG+RMsOqBPW114iZ2/8T9Pf6dcIib6wbrVNX47n2/oNkKWjrVOA1tb+yDJ6l3j5gXLI+o06bYeX27GOU/N4voZUZdDHj2N5qhDmG/IVUYQHb1nQ9BMtu8y6Zn3QI39en+KXJ9pj+YRfskcog/GTFmsU+/Ud0GocaCJ6iPkbnf4SkHaSga2nSNiECAS7ZtuL5Y7iAhPf6c8GzZ4xQkpPxKJGBwkM/wpFFn11luz6fWho5PoGCYVuWLU0WCvgN/o3asC45D4woQW/NGJbJhRmw73Zzj6CPXz2KH9a9b/FYUoY070ivlDa3Wc00MK+mo6erXQBecnclh34qRnT4UfdI/Xan4zqfdrTtH7fEUzWxlHGT0yxvDR9Cg8g4A6wsx/qL9mDciWSDqueN7TOc4/6vwbpL61biTpMd6l1mzFa5ByQUdA=
