[tox]
envlist =
    ruff,
    py39,
    py310,
    py311,
    py312,
    py313,
    py314,
    coverage,

[testenv]
usedevelop = True
extras = test
deps =
    pytest
    pytest-timeout
commands = py.test []

[testenv:coverage]
basepython = python3
deps =
    {[testenv]deps}
    pytest-cov
    coverage
    coverage-python-version
commands =
    py.test --cov=src --cov-report=html []

[testenv:ruff]
basepython = python3
skip_install = true
deps = ruff
commands = ruff check src
